"""create_group_sharing_tables

Revision ID: 4bc2dbb6125b
Revises: ccf8dcfe27d3
Create Date: 2026-08-25 12:54:20.729103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bc2dbb6125b'
down_revision: Union[str, Sequence[str], None] = 'ccf8dcfe27d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_id'), 'groups', ['id'], unique=False)
    op.create_index(op.f('ix_groups_owner_id'), 'groups', ['owner_id'], unique=False)
    op.create_table('group_expenses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('split_method', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_expenses_category_id'), 'group_expenses', ['category_id'], unique=False)
    op.create_index(op.f('ix_group_expenses_date'), 'group_expenses', ['date'], unique=False)
    op.create_index(op.f('ix_group_expenses_group_id'), 'group_expenses', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_expenses_id'), 'group_expenses', ['id'], unique=False)
    op.create_table('group_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'user_id', name='uq_group_member_user')
    )
    op.create_index(op.f('ix_group_members_group_id'), 'group_members', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_members_id'), 'group_members', ['id'], unique=False)
    op.create_index(op.f('ix_group_members_user_id'), 'group_members', ['user_id'], unique=False)
    op.create_table('group_settlements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('payer_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_settlements_date'), 'group_settlements', ['date'], unique=False)
    op.create_index(op.f('ix_group_settlements_group_id'), 'group_settlements', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_settlements_id'), 'group_settlements', ['id'], unique=False)
    op.create_index(op.f('ix_group_settlements_payer_id'), 'group_settlements', ['payer_id'], unique=False)
    op.create_index(op.f('ix_group_settlements_receiver_id'), 'group_settlements', ['receiver_id'], unique=False)
    op.create_table('group_expense_participants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_expense_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('share_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('calculated_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['group_expense_id'], ['group_expenses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_expense_id', 'user_id', name='uq_group_expense_participant_user')
    )
    op.create_index(op.f('ix_group_expense_participants_group_expense_id'), 'group_expense_participants', ['group_expense_id'], unique=False)
    op.create_index(op.f('ix_group_expense_participants_id'), 'group_expense_participants', ['id'], unique=False)
    op.create_index(op.f('ix_group_expense_participants_user_id'), 'group_expense_participants', ['user_id'], unique=False)
    op.create_table('group_expense_payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_expense_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['group_expense_id'], ['group_expenses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_expense_id', 'user_id', name='uq_group_expense_payment_user')
    )
    op.create_index(op.f('ix_group_expense_payments_group_expense_id'), 'group_expense_payments', ['group_expense_id'], unique=False)
    op.create_index(op.f('ix_group_expense_payments_id'), 'group_expense_payments', ['id'], unique=False)
    op.create_index(op.f('ix_group_expense_payments_user_id'), 'group_expense_payments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_group_expense_payments_user_id'), table_name='group_expense_payments')
    op.drop_index(op.f('ix_group_expense_payments_id'), table_name='group_expense_payments')
    op.drop_index(op.f('ix_group_expense_payments_group_expense_id'), table_name='group_expense_payments')
    op.drop_table('group_expense_payments')
    op.drop_index(op.f('ix_group_expense_participants_user_id'), table_name='group_expense_participants')
    op.drop_index(op.f('ix_group_expense_participants_id'), table_name='group_expense_participants')
    op.drop_index(op.f('ix_group_expense_participants_group_expense_id'), table_name='group_expense_participants')
    op.drop_table('group_expense_participants')
    op.drop_index(op.f('ix_group_settlements_receiver_id'), table_name='group_settlements')
    op.drop_index(op.f('ix_group_settlements_payer_id'), table_name='group_settlements')
    op.drop_index(op.f('ix_group_settlements_id'), table_name='group_settlements')
    op.drop_index(op.f('ix_group_settlements_group_id'), table_name='group_settlements')
    op.drop_index(op.f('ix_group_settlements_date'), table_name='group_settlements')
    op.drop_table('group_settlements')
    op.drop_index(op.f('ix_group_members_user_id'), table_name='group_members')
    op.drop_index(op.f('ix_group_members_id'), table_name='group_members')
    op.drop_index(op.f('ix_group_members_group_id'), table_name='group_members')
    op.drop_table('group_members')
    op.drop_index(op.f('ix_group_expenses_id'), table_name='group_expenses')
    op.drop_index(op.f('ix_group_expenses_group_id'), table_name='group_expenses')
    op.drop_index(op.f('ix_group_expenses_date'), table_name='group_expenses')
    op.drop_index(op.f('ix_group_expenses_category_id'), table_name='group_expenses')
    op.drop_table('group_expenses')
    op.drop_index(op.f('ix_groups_owner_id'), table_name='groups')
    op.drop_index(op.f('ix_groups_id'), table_name='groups')
    op.drop_table('groups')
    # ### end Alembic commands ###
